name: '[Prod] Deploy'
on:
  push:
    tags:
      - 'v**'
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Download compiled website
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ vars.FTP_SERVER }} 
        user: ${{ vars.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist"
